# Generated by Django 5.0.3 on 2025-10-09 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('cgpa', models.FloatField()),
                ('branch', models.CharField(max_length=50)),
                ('resume_url', models.FileField(blank=True, upload_to='resumes/')),
                ('skills', models.TextField(blank=True)),
            ],
        ),
    ]
