# Generated by Django 5.0.3 on 2025-10-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=100)),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(default='open', max_length=20)),
            ],
        ),
    ]
