# Generated by Django 5.0.3 on 2025-11-01 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=20)),
                ('application_date', models.DateField(default=datetime.date.today)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
    ]
